name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # Jika Anda memiliki file requirements.txt, Anda bisa menginstall dependencies di sini
        echo "No dependencies to install."

    - name: Compile code
      run: |
        echo "Compiling code..."

    - name: Run the program
      run: |
        python app.py